window.FAMILY_CONFIG={title:"Keluarga Besar",rootId:"ahmad",people:[
{id:"ahmad",name:"Ahmad Santoso",gender:"M",birth:"1935",death:"2010",role:"Kakek",spouseIds:["siti"],parentIds:[],photo:""},
{id:"siti",name:"Siti Aminah",gender:"F",birth:"1938",death:"2018",role:"Nenek",spouseIds:["ahmad"],parentIds:[],photo:""},
{id:"budi",name:"Budi Santoso",gender:"M",birth:"1960",death:"",role:"Anak",spouseIds:["ani"],parentIds:["ahmad","siti"],photo:""},
{id:"ani",name:"Ani Rahma",gender:"F",birth:"1963",death:"",role:"Menantu",spouseIds:["budi"],parentIds:[],photo:""},
{id:"dedi",name:"Dedi Wijaya",gender:"M",birth:"1962",death:"",role:"Anak",spouseIds:[],parentIds:["ahmad","siti"],photo:""},
{id:"rina",name:"Rina Santoso",gender:"F",birth:"1967",death:"",role:"Anak",spouseIds:["andi"],parentIds:["ahmad","siti"],photo:""},
{id:"andi",name:"Andi Pratama",gender:"M",birth:"1965",death:"",role:"Menantu",spouseIds:["rina"],parentIds:[],photo:""},
{id:"citra",name:"Citra Budi",gender:"F",birth:"1988",death:"",role:"Cucu",spouseIds:[],parentIds:["budi","ani"],photo:""},
{id:"fajar",name:"Fajar Budi",gender:"M",birth:"1991",death:"",role:"Cucu",spouseIds:[],parentIds:["budi","ani"],photo:""}]};